name: Publish app to Google Play

on:
  workflow_dispatch:

env:
  GITHUB_USERNAME: ${{ secrets.SECRET_GITHUB_USERNAME }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.SECRET_GITHUB_ACCESS_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: ${{ vars.RUNNING_HOST }}

    steps:
      - name: Check out project
        uses: actions/checkout@v3

      - name: Setup JDK Version
        uses: actions/setup-java@v3
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}

      - name: Download AAB
        uses: actions/download-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/

      - name: Publish to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}
          packageName: com.yitianyitiandan.cicdtest
          releaseFile: app/build/outputs/bundle/release/app-release.aab
          track: alpha
