  name: CICD
  on:
    workflow_dispatch:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]

  jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Check out project
            uses: actions/checkout@v3

          - name: Setup JDK
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'zulu'

          - name: Grant execute permission for gradlew
            run: chmod +x gradlew

          - name: Build Release Apk
            run: ./gradlew assembleRelease