  name: CICD
  on:
    workflow_dispatch:
    push:
        branches: [ develop, github_action_cicd ]
    pull_request:
        branches: [ develop ]

  jobs:
    build:
        runs-on: macos-latest

        steps:
          - name: Check out project
            uses: actions/checkout@v3

          - name: Setup JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'zulu'

          - name: Grant execute permission for gradlew
            run: chmod +x gradlew

          - name: Set up keystore
            env:
              ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_FILE_BASE64 }}
            run: |
              echo $ENCODED_KEYSTORE | base64 -D > keystore.jks

          - name: Build Release Apk
            env:
              GITHUB_USERNAME: ${{ secrets.SECRET_GITHUB_USERNAME }}
              GITHUB_ACCESS_TOKEN: ${{ secrets.SECRET_GITHUB_ACCESS_TOKEN }}
              STORE_PASSWORD: ${{ secrets.KEYSTORE_KEY_STORE_PASSWORD }}
              KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
              KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
            run: ./gradlew assembleRelease