  name: CICD
  on:
    workflow_dispatch:
    push:
        branches: [ develop, github_action_cicd ]
    pull_request:
        branches: [ develop ]

  jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Check out project
            uses: actions/checkout@v3

          - name: Setup JDK
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'zulu'

          - name: Grant execute permission for gradlew
            run: chmod +x gradlew

          - name: Build Release Apk
            env:
              GITHUB_USERNAME: ${{ secrets.SECRET_GITHUB_USERNAME }}
              GITHUB_ACCESS_TOKEN: ${{ secrets.SECRET_GITHUB_ACCESS_TOKEN }}
            run: ./gradlew assembleRelease